<?php include_once("includes/basic_includes.php");?>
<?php include_once("functions.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<title>Find Your Perfect Partner - Makemylove
 | Terms :: Make My Love
</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="css/bootstrap-3.1.1.min.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<!-- Custom Theme files -->
<link href="css/style.css" rel='stylesheet' type='text/css' />
<link href='//fonts.googleapis.com/css?family=Oswald:300,400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
<!----font-Awesome----->
<link href="css/font-awesome.css" rel="stylesheet"> 
<!----font-Awesome----->
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
</head>
<body>
<!-- ============================  Navigation Start =========================== -->
<?php include_once("includes/navigation.php");?>
<!-- ============================  Navigation End ============================ -->
<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.php"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Terms and Conditions</li>
     </ul>
   </div>
   <div class="terms_1">
	    <h3>Welcome to Marital</h3>	
	    <ul class="feature_list">
			<li><a href="#">1. This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.</a></li>
			<li><a href="#">2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and the terms and conditions for access or usage of www.communitymatrimony.com/www.Christianmatrimony.com (the "Website/Applications"(APP).</a></li>
			<li><a href="#">3.Please read the following terms and conditions very carefully as your use of the Website and associated CM Services (as defined below) is subject to your acceptance of and compliance with the following terms and conditions including the applicable policies which are incorporated herein by way of reference and as amended from time to time (the "Terms and conditions").</a></li>
			<li><a href="#">4. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS herein, SO PLEASE READ THE TERMS and conditions CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms and Conditions of use of website, You also accept and agree that you have read, understood and are bound by these Terms and conditions, regardless of how you/CM member subscribe to or use the CM Services. If you do not want to be bound by the Terms and Conditions, you must not use the Website or App-Applications or the CM Services..</a></li>
			<li><a href="#">5. In these Terms, references to "You" or "User" or "CM member" shall mean the end user accessing the Website/CM services, its contents or using the CM Services offered. "CM Services" means a collective reference to the Christian Matrimony service provided by Matrimony.com Limited ,CIN : U63090TN2001PLC047432,a company under the provisions of companies act, 2013 and having its registered office at No.94, TVH Beliciaa Towers, Tower - 2, 10th Floor, MRC Nagar, Chennai, Tamil Nadu - 600 028('MCL/Company').</a></li>
			<li><a href="#">6.The profiles in the database of CM are classified broadly on the basis of religion and community for the ease and convenience of its member / customer.</a></li>
			<li><a href="#">7.CM Members are provided with free/paid access for searching profiles from the database of CM, as per the partner preference set by you (on the Website/Applications - (App) and you shortlist the prospective alliances yourself.</a></li>
		</ul>
	    <h5>Grievance Cell </h5>   
	    <ul class="feature_list feature_list1">
			<li><a href="#">In the event you come across any violation by another user including but not limited to having content in the web site that is obscene, menacing, grossly offensive, harming minors, infringing copyright, patents, etc., or another user is impersonating etc. you may then please be free to provide your concerns in writing or email us with digital signature to,"Email: grievanceofficer@matrimony.com".</a></li>
			<li><a href="#">The Grievance officer shall be available between 10 am till 6 pm Indian Standard Time from Monday to Saturday excluding Sunday and public holidays in India. The Grievance officer is appointed as per Rule 3 (11) of The Information Technology (Intermediaries Guidelines) Rules, 2011. Any and all complaints to the Grievance Officer shall be in writing.</a></li>
			<li><a href="#">The Grievance Officer shall handle complaints in relation to the following violation by the User of computer resource as the User is not entitled to host, display, upload, modify, publish, transmit, update or share any information on the Website/App.</a></li>
			<li><a href="#">You and the prospect are both registered CM members and are bound by these terms and condition. We request you to follow the guidelines of safe matrimony (see URL https://www.christianmatrimony.com/safematrimony/ and give truthful information about yourself on the Website/App to avoid dispute between you and the prospect.</a></li>
			<li><a href="#"> You acknowledge that you are responsible for the content (mandatory or optional content you provided on our website) and information including the profile details, photograph and other content(s) keyed in the relevant field of the Website/App at the time of the creation of the CM profile or subsequently modified by you and also for all the post and communication (including personalized messages sent by CM paid members) with other member(s). You hereby represent and warrant that you own all rights, title and interest in your content/information or have the necessary licenses, rights, consents, and permissions to provide the said content/information. However, by submitting the content/information to CM, you hereby grant CM a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, prepare derivative works of, display, publish, communicate to the public, law enforcement agencies, courts, and the CM's business and services, including without limitation for promoting, communicating to the public and redistributing part or all of the content/information (and derivative works thereof) in any media formats and through any media channels. CM also reserves the right to block the registration of your profile on Website/App, if any, in the case of your contact details/links being entered in irrelevant fields or if there are errors in data entered by the CM members in their profile.</a></li>
			<li><a href="#"> Notwithstanding anything contained herein, CM reserves the absolute right to delete, in any manner as it deems fit, any content of any profile listing placed on CM/website/App (once such instance come to CM notice) in order to ensure compliance with the rules of such placement, prima facie accuracy and the prevailing laws in force for the time being, especially those relating to providing any obscene, libelous, blasphemous, slanderous, defamatory or invasive of another person's (deceased or alive) right of privacy or publicity, or that may reasonably be deemed to be harmful, vulgar, pornographic, abusive, harassing, threatening, hateful, objectionable with respect to race, religion, creed, nationality, gender or otherwise unfit for reproduction; or suggests or encourages unfair or illegal /indecent, unlawful activity. CM also reserves the right to block/ delete / suspend the profile which might be offensive, illegal or that might violate the rights, harm or threaten the safety of our office bearers/employees (including undue communication with any employee) and/or other registered prospects.</a></li>
			<li><a href="#">Your access to and use of the CM Services or any content is at your own risk. YOU UNDERSTAND AND AGREE THAT THE CMSERVICES ARE PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS. WITHOUT LIMITING THE FOREGOING, TO THE FULL EXTENT PERMITTED BY LAW, CMDISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. CM does not warrant that the Website/App, its servers, or e-mail sent from CM are free of viruses or other harmful components. CM will not be liable for any damages of any kind arising from the use of this CM Website/App, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</a></li>
		</ul>
		
     </div>
   </div>
</div>


<?php include_once("footer.php");?>

</body>
</html>	